import sqlite3
import datetime
#Creating Database
conn = sqlite3.connect('ncov.db') 
c = conn.cursor()

#Creating table
c.execute('CREATE TABLE IF NOT EXISTS nCOVactive(dta TEXT,active INT,ind INT)')
#except:
 #   print("Table already created")

now = datetime.datetime.now()
#Inserting values
#c.execute("DROP TABLE nCOVactive")
#c.execute("INSERT INTO nCOVactive VALUES('6 A', 4267,1)")
#c.execute("INSERT INTO nCOVactive VALUES('7 A', 4723,2)")
#c.execute("INSERT INTO nCOVactive VALUES('8 A', 5232,3)")
#c.execute("INSERT INTO nCOVactive VALUES('9 A', 5863,4)")
#c.execute("INSERT INTO nCOVactive VALUES('10 A', 6577,5)")
#c.execute("INSERT INTO nCOVactive VALUES('11 A', 7189,6)")
#c.execute("INSERT INTO nCOVactive VALUES('12 A', 7794,7)")
#c.execute("INSERT INTO nCOVactive VALUES('13 A', 8914,8)")
#c.execute("INSERT INTO nCOVactive VALUES('14 A', 9735,9)")
#c.execute("INSERT INTO nCOVactive VALUES('15 A', 10440,10)")
#c.execute("INSERT INTO nCOVactive VALUES('16 A', 11214,11)")
#c.execute("INSERT INTO nCOVactive VALUES('17 A', 11825,12)")
#c.execute("INSERT INTO nCOVactive VALUES('18 A', 13381,13)")
#c.execute("INSERT INTO nCOVactive VALUES('19 A', 14202,14)")
#c.execute("INSERT INTO nCOVactive VALUES('20 A', 14674,15)")
#c.execute("INSERT INTO nCOVactive VALUES('21 A', 15460,16)")
#c.execute("INSERT INTO nCOVactive VALUES('22 A', 16319,17)")
#c.execute("INSERT INTO nCOVactive VALUES('23 A', 17306,18)")
#c.execute("INSERT INTO nCOVactive VALUES('24 A', 18171,19)")
#c.execute("INSERT INTO nCOVactive VALUES('25 A', 19519,20)")
#c.execute("INSERT INTO nCOVactive VALUES('26 A', 20486,21)")
#c.execute("INSERT INTO nCOVactive VALUES('27 A', 22010,22)")
#c.execute("INSERT INTO nCOVactive VALUES('28 A', 22982,23)")
#c.execute("UPDATE nCOVactive SET dta='28' WHERE active='22010'")
#c.execute("UPDATE nCOVactive SET dta='29' WHERE active='22982'")
#c.execute("INSERT INTO nCOVactive VALUES('29 A',23546,24)")
#c.execute("INSERT INTO nCOVactive VALUES('30 A',24162,25)")
c.execute("UPDATE nCOVactive SET ind='28' WHERE dta='4M'")
c.execute("UPDATE nCOVactive SET ind='29' WHERE dta='5M'")
c.execute("UPDATE nCOVactive SET ind='30' WHERE dta='6M'")
c.execute("UPDATE nCOVactive SET ind='31' WHERE dta='7M'")
c.execute("UPDATE nCOVactive SET ind='32' WHERE dta='8M'")
c.execute("UPDATE nCOVactive SET ind='33' WHERE dta='9M'")
c.execute("UPDATE nCOVactive SET ind='34' WHERE dta='10M'")
c.execute("UPDATE nCOVactive SET ind='35' WHERE dta='11M'")
c.execute("UPDATE nCOVactive SET ind='36' WHERE dta='12M'")
c.execute("UPDATE nCOVactive SET ind='37' WHERE dta='13M'")
c.execute("UPDATE nCOVactive SET ind='38' WHERE dta='14M'")
c.execute("UPDATE nCOVactive SET ind='39' WHERE dta='15M'")
c.execute("UPDATE nCOVactive SET ind='40' WHERE dta='16M'")
c.execute("UPDATE nCOVactive SET ind='41' WHERE dta='17M'")
c.execute("UPDATE nCOVactive SET ind='41' WHERE dta='18M'")
c.execute("UPDATE nCOVactive SET ind='43' WHERE dta='19M'")
c.execute("UPDATE nCOVactive SET ind='44' WHERE dta='20M'")
c.execute("UPDATE nCOVactive SET ind='45' WHERE dta='21M'")
c.execute("UPDATE nCOVactive SET ind='46' WHERE dta='22M'")
c.execute("UPDATE nCOVactive SET ind='47' WHERE dta='23M'")
c.execute("UPDATE nCOVactive SET ind='48' WHERE dta='24M'")
c.execute("UPDATE nCOVactive SET ind='49' WHERE dta='50M'")
#c.execute("UPDATE nCOVactive SET dta='7A' WHERE dta='7 A'")
#c.execute("UPDATE nCOVactive SET dta='8A' WHERE dta='8 A'")
#c.execute("UPDATE nCOVactive SET dta='9A' WHERE dta='9 A'")
#c.execute("UPDATE nCOVactive SET dta='10A' WHERE dta='10 A'")
#c.execute("UPDATE nCOVactive SET dta='11A' WHERE dta='11 A'")
#c.execute("UPDATE nCOVactive SET dta='12A' WHERE dta='12 A'")
#c.execute("UPDATE nCOVactive SET dta='13A' WHERE dta='13 A'")
#c.execute("UPDATE nCOVactive SET dta='14A' WHERE dta='14 A'")
#c.execute("UPDATE nCOVactive SET dta='15A' WHERE dta='15 A'")
#c.execute("UPDATE nCOVactive SET dta='16A' WHERE dta='16 A'")
#c.execute("UPDATE nCOVactive SET dta='17A' WHERE dta='17 A'")
#c.execute("UPDATE nCOVactive SET dta='18A' WHERE dta='18 A'")
#c.execute("UPDATE nCOVactive SET dta='19A' WHERE dta='19 A'")
#c.execute("UPDATE nCOVactive SET dta='20A' WHERE dta='20 A'")
#c.execute("UPDATE nCOVactive SET dta='21A' WHERE dta='21 A'")
#c.execute("UPDATE nCOVactive SET dta='22A' WHERE dta='22 A'")
#c.execute("UPDATE nCOVactive SET dta='23A' WHERE dta='23 A'")
#c.execute("UPDATE nCOVactive SET dta='24A' WHERE dta='24 A'")
#c.execute("UPDATE nCOVactive SET dta='25A' WHERE dta='25 A'")
#c.execute("UPDATE nCOVactive SET dta='26A' WHERE dta='26 A'")
#c.execute("UPDATE nCOVactive SET dta='27A' WHERE dta='27 A'")
#c.execute("UPDATE nCOVactive SET dta='28A' WHERE dta='28 A'")
#c.execute("UPDATE nCOVactive SET dta='29A' WHERE dta='29 A'")
#c.execute("UPDATE nCOVactive SET dta='30A' WHERE dta='30 A'")
#c.execute("UPDATE nCOVactive SET dta='1M' WHERE dta='1 M'")
#c.execute("UPDATE nCOVactive SET dta='2M' WHERE dta='2 M'")
#c.execute("UPDATE nCOVactive SET dta='3M' WHERE dta='3 M'")
#c.execute("UPDATE nCOVactive SET dta='4M' WHERE dta='4 M'")
#c.execute("UPDATE nCOVactive SET dta='5M' WHERE dta='5 M'")
#c.execute("UPDATE nCOVactive SET dta='6M' WHERE dta='6 M'")
#c.execute("UPDATE nCOVactive SET dta='7M' WHERE dta='7 M'")
#c.execute("UPDATE nCOVactive SET dta='8M' WHERE dta='8 M'")
#c.execute("UPDATE nCOVactive SET dta='9M' WHERE dta='9 M'")
#c.execute("UPDATE nCOVactive SET dta='10M' WHERE dta='10 M'")
#c.execute("UPDATE nCOVactive SET dta='11M' WHERE dta='11 M'")
#c.execute("UPDATE nCOVactive SET dta='12M' WHERE dta='12 M'")
#c.execute("UPDATE nCOVactive SET active='31967' WHERE dta='5 M'")
#c.execute("UPDATE nCOVactive SET dta='16M' WHERE ind='41'")
#c.execute("INSERT INTO nCOVactive VALUES('6J',115942,61)")
c.execute("DELETE FROM nCOVactive WHERE dta='13J'")
conn.commit()
c.execute("SELECT * FROM nCOVactive")
for i in c.fetchall():
    print(i[0],i[1],i[2])
c.close()
conn.close()
