import sqlite3
import datetime
#Creating Database
conn = sqlite3.connect('ncov.db') 
c = conn.cursor()

#Creating table
c.execute('CREATE TABLE IF NOT EXISTS nCOVe(dte TEXT,pe INT, ind INT)')
#except:
 #   print("Table already created")

now = datetime.datetime.now()
#Inserting values
#c.execute("DROP TABLE nCOVe")
#c.execute("DELETE FROM nCOVe WHERE pm='50000'")
#c.execute("INSERT INTO nCOVe VALUES('6 A', 4281,1)")
#c.execute("INSERT INTO nCOVe VALUES('7 A', 4789,2)")
#c.execute("INSERT INTO nCOVe VALUES('8 A', 5274,3)")
#c.execute("INSERT INTO nCOVe VALUES('9 A', 5865,4)")
#c.execute("INSERT INTO nCOVe VALUES('10 A', 6761,5)")
#c.execute("INSERT INTO nCOVe VALUES('11 A', 7529,6)")
#c.execute("INSERT INTO nCOVe VALUES('12 A', 8447,7)")
#c.execute("INSERT INTO nCOVe VALUES('13 A', 9352,8)")
#c.execute("INSERT INTO nCOVe VALUES('14 A', 10815,9)")
#c.execute("INSERT INTO nCOVe VALUES('15 A', 11933,10)")
#c.execute("INSERT INTO nCOVe VALUES('16 A', 12759,11)")
#c.execute("INSERT INTO nCOVe VALUES('17 A', 13835,12)")
#c.execute("INSERT INTO nCOVe VALUES('18 A', 14792,13)")
#c.execute("INSERT INTO nCOVe VALUES('19 A', 16116,14)")
#c.execute("INSERT INTO nCOVe VALUES('20 A', 17656,15)")
#c.execute("INSERT INTO nCOVe VALUES('21 A', 18985,16)")
#c.execute("INSERT INTO nCOVe VALUES('22 A', 20471,17)")
#c.execute("INSERT INTO nCOVe VALUES('23 A', 21700,18)")
#c.execute("INSERT INTO nCOVe VALUES('24 A', 23452,19)")
#c.execute("INSERT INTO nCOVe VALUES('25 A', 24942,20)")
#c.execute("INSERT INTO nCOVe VALUES('26 A', 26917,21)")
#c.execute("INSERT INTO nCOVe VALUES('27 A', 28380,22)")
#c.execute("INSERT INTO nCOVe VALUES('28 A', 29974,23)")
#c.execute("INSERT INTO nCOVe VALUES('29 A', 31787,24)")
#c.execute("INSERT INTO nCOVe VALUES('30 A', 33610,25)")
c.execute("UPDATE nCOVe SET dte='6A' WHERE dte='6 A'")
c.execute("UPDATE nCOVe SET dte='7A' WHERE dte='7 A'")
c.execute("UPDATE nCOVe SET dte='8A' WHERE dte='8 A'")
c.execute("UPDATE nCOVe SET dte='9A' WHERE dte='9 A'")
c.execute("UPDATE nCOVe SET dte='10A' WHERE dte='10 A'")
c.execute("UPDATE nCOVe SET dte='11A' WHERE dte='11 A'")
c.execute("UPDATE nCOVe SET dte='12A' WHERE dte='12 A'")
c.execute("UPDATE nCOVe SET dte='13A' WHERE dte='13 A'")
c.execute("UPDATE nCOVe SET dte='14A' WHERE dte='14 A'")
c.execute("UPDATE nCOVe SET dte='15A' WHERE dte='15 A'")
c.execute("UPDATE nCOVe SET dte='16A' WHERE dte='16 A'")
c.execute("UPDATE nCOVe SET dte='17A' WHERE dte='17 A'")
c.execute("UPDATE nCOVe SET dte='18A' WHERE dte='18 A'")
c.execute("UPDATE nCOVe SET dte='19A' WHERE dte='19 A'")
c.execute("UPDATE nCOVe SET dte='20A' WHERE dte='20 A'")
c.execute("UPDATE nCOVe SET dte='21A' WHERE dte='21 A'")
c.execute("UPDATE nCOVe SET dte='22A' WHERE dte='22 A'")
c.execute("UPDATE nCOVe SET dte='23A' WHERE dte='23 A'")
c.execute("UPDATE nCOVe SET dte='24A' WHERE dte='24 A'")
c.execute("UPDATE nCOVe SET dte='25A' WHERE dte='25 A'")
c.execute("UPDATE nCOVe SET dte='26A' WHERE dte='26 A'")
c.execute("UPDATE nCOVe SET dte='27A' WHERE dte='27 A'")
c.execute("UPDATE nCOVe SET dte='28A' WHERE dte='28 A'")
c.execute("UPDATE nCOVe SET dte='29A' WHERE dte='29 A'")
c.execute("UPDATE nCOVe SET dte='30A' WHERE dte='30 A'")
c.execute("UPDATE nCOVe SET dte='1M' WHERE dte='1 M'")
c.execute("UPDATE nCOVe SET dte='2M' WHERE dte='2 M'")
c.execute("UPDATE nCOVe SET dte='3M' WHERE dte='3 M'")
c.execute("UPDATE nCOVe SET dte='4M' WHERE dte='4 M'")
c.execute("UPDATE nCOVe SET dte='5M' WHERE dte='5 M'")
c.execute("UPDATE nCOVe SET dte='6M' WHERE dte='6 M'")
c.execute("UPDATE nCOVe SET dte='7M' WHERE dte='7 M'")
c.execute("UPDATE nCOVe SET dte='8M' WHERE dte='8 M'")
c.execute("UPDATE nCOVe SET dte='9M' WHERE dte='9 M'")
c.execute("UPDATE nCOVe SET dte='10M' WHERE dte='10 M'")
c.execute("UPDATE nCOVe SET dte='11M' WHERE dte='11 M'")
c.execute("UPDATE nCOVe SET dte='12M' WHERE dte='12 M'")
#c.execute("DELETE FROM nCOVe WHERE dte='7J'")
c.execute("DELETE FROM nCOVe WHERE dte='13J'")
#c.execute("DELETE FROM nCOVe WHERE dte='2J'")
#c.execute("INSERT INTO nCOVe VALUES('31M',182143,55)")
#c.execute("INSERT INTO nCOVe VALUES('1J',190535,56)")
#c.execute("INSERT INTO nCOVe VALUES('2J',198706,57)")
conn.commit()
c.execute("SELECT * FROM nCOVe")
for i in c.fetchall():
    print(i[0],i[1],i[2])
c.close()
conn.close()
